services:
  osfrontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://osbackend:8000
      - FASTAPI_URL=http://osbackend:8000
    depends_on:
      - osbackend
    networks:
      - os-app-network

  osbackend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - /app/_pycache_
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - os-app-network

networks:
  os-app-network:
    driver: bridge